import { neon } from "@neondatabase/serverless"
import { drizzle } from "drizzle-orm/neon-http"
import { companiesTable, contactsTable, dealsTable, activitiesTable } from "./schema"

async function seed() {
  const DATABASE_URL = process.env.DATABASE_URL
  
  if (!DATABASE_URL) {
    console.error("❌ DATABASE_URL environment variable is required")
    console.log("\nTo set up your database:")
    console.log("1. Create a free PostgreSQL database at https://neon.tech")
    console.log("2. Copy your connection string")
    console.log("3. Add it to .env.local as DATABASE_URL")
    process.exit(1)
  }

  const sql = neon(DATABASE_URL)
  const db = drizzle(sql)

  console.log("🌱 Seeding database...")

  // Clear existing data
  await db.delete(activitiesTable)
  await db.delete(dealsTable)
  await db.delete(contactsTable)
  await db.delete(companiesTable)

  // Insert companies - Major Asset Managers, Wealth Managers, and FinTech vendors
  const companies = await db
    .insert(companiesTable)
    .values([
      {
        name: "BlackRock",
        industry: "Asset Management",
        website: "https://www.blackrock.com",
        phone: "+1 212-810-5300",
        email: "contact@blackrock.com",
        address: "50 Hudson Yards",
        city: "New York",
        state: "NY",
        zipCode: "10001",
        country: "United States",
        employeeCount: 19800,
        revenue: 17800000000,
        description: "World's largest asset manager with $10+ trillion AUM. Key products include iShares ETFs and Aladdin risk management platform.",
      },
      {
        name: "Vanguard Group",
        industry: "Asset Management",
        website: "https://www.vanguard.com",
        phone: "+1 610-669-1000",
        email: "institutional@vanguard.com",
        address: "100 Vanguard Boulevard",
        city: "Malvern",
        state: "PA",
        zipCode: "19355",
        country: "United States",
        employeeCount: 18600,
        revenue: 7500000000,
        description: "Second largest asset manager globally. Pioneer in index investing and low-cost mutual funds.",
      },
      {
        name: "UBS Asset Management",
        industry: "Wealth Management",
        website: "https://www.ubs.com",
        phone: "+41 44 234 1111",
        email: "am-contact@ubs.com",
        address: "Bahnhofstrasse 45",
        city: "Zurich",
        state: "ZH",
        zipCode: "8001",
        country: "Switzerland",
        employeeCount: 72000,
        revenue: 34500000000,
        description: "Global wealth manager and investment bank. Leading position in ultra-high-net-worth client segment.",
      },
      {
        name: "State Street Global Advisors",
        industry: "Asset Management",
        website: "https://www.ssga.com",
        phone: "+1 617-786-3000",
        email: "institutional@ssga.com",
        address: "One Lincoln Street",
        city: "Boston",
        state: "MA",
        zipCode: "02111",
        country: "United States",
        employeeCount: 39000,
        revenue: 12100000000,
        description: "Third largest asset manager. Inventor of the first US ETF (SPY). Strong custody and administration services.",
      },
      {
        name: "Northern Trust Asset Management",
        industry: "Asset Management",
        website: "https://www.northerntrust.com",
        phone: "+1 312-630-6000",
        email: "assetmanagement@ntrs.com",
        address: "50 South La Salle Street",
        city: "Chicago",
        state: "IL",
        zipCode: "60603",
        country: "United States",
        employeeCount: 23000,
        revenue: 6500000000,
        description: "Leading provider of asset management, custody, and wealth management services to institutional and affluent investors.",
      },
      {
        name: "Charles River Development",
        industry: "FinTech - Investment Management",
        website: "https://www.crd.com",
        phone: "+1 781-622-1000",
        email: "info@crd.com",
        address: "380 Stuart Street",
        city: "Boston",
        state: "MA",
        zipCode: "02116",
        country: "United States",
        employeeCount: 1200,
        revenue: 450000000,
        description: "Leading provider of investment management solutions. Charles River IMS is used by major asset managers for front-to-back operations.",
      },
      {
        name: "SimCorp",
        industry: "FinTech - Investment Management",
        website: "https://www.simcorp.com",
        phone: "+45 35 44 88 00",
        email: "info@simcorp.com",
        address: "Weidekampsgade 16",
        city: "Copenhagen",
        state: "",
        zipCode: "2300",
        country: "Denmark",
        employeeCount: 2200,
        revenue: 580000000,
        description: "Provider of SimCorp Dimension, an integrated investment management platform for buy-side institutions globally.",
      },
      {
        name: "Temenos",
        industry: "FinTech - Banking",
        website: "https://www.temenos.com",
        phone: "+41 22 708 11 50",
        email: "info@temenos.com",
        address: "2 Rue de l'Ecole-de-Chimie",
        city: "Geneva",
        state: "",
        zipCode: "1205",
        country: "Switzerland",
        employeeCount: 7500,
        revenue: 980000000,
        description: "Global leader in banking software. Temenos Transact and Wealth platforms power many private banks and wealth managers.",
      },
      {
        name: "SS&C Technologies",
        industry: "FinTech - Financial Services",
        website: "https://www.ssctech.com",
        phone: "+1 860-298-4500",
        email: "info@sscinc.com",
        address: "80 Lamberton Road",
        city: "Windsor",
        state: "CT",
        zipCode: "06095",
        country: "United States",
        employeeCount: 27000,
        revenue: 5600000000,
        description: "Provider of financial services software including Advent Geneva, Eze, and fund administration services.",
      },
      {
        name: "Broadridge Financial",
        industry: "FinTech - Financial Services",
        website: "https://www.broadridge.com",
        phone: "+1 516-472-5400",
        email: "info@broadridge.com",
        address: "5 Dakota Drive",
        city: "Lake Success",
        state: "NY",
        zipCode: "11042",
        country: "United States",
        employeeCount: 14000,
        revenue: 5900000000,
        description: "Global fintech leader providing investor communications, technology-driven solutions for broker-dealers and asset managers.",
      },
    ])
    .returning()

  console.log(`✅ Inserted ${companies.length} companies`)

  // Insert contacts
  const contacts = await db
    .insert(contactsTable)
    .values([
      {
        firstName: "Robert",
        lastName: "Kapito",
        email: "r.kapito@blackrock.com",
        phone: "+1 212-810-5301",
        jobTitle: "President",
        companyId: companies[0].id,
        city: "New York",
        state: "NY",
        country: "United States",
        notes: "Co-founder of BlackRock. Key decision maker for strategic technology investments.",
      },
      {
        firstName: "Sarah",
        lastName: "Chen",
        email: "s.chen@blackrock.com",
        phone: "+1 212-810-5402",
        jobTitle: "Head of Technology Strategy",
        companyId: companies[0].id,
        city: "New York",
        state: "NY",
        country: "United States",
        notes: "Leads Aladdin platform strategy. Previously at Goldman Sachs.",
      },
      {
        firstName: "Tim",
        lastName: "Buckley",
        email: "t.buckley@vanguard.com",
        phone: "+1 610-669-1001",
        jobTitle: "Chief Executive Officer",
        companyId: companies[1].id,
        city: "Malvern",
        state: "PA",
        country: "United States",
        notes: "CEO since 2018. Strong advocate for low-cost investing and technology modernization.",
      },
      {
        firstName: "Michelle",
        lastName: "Santos",
        email: "m.santos@vanguard.com",
        phone: "+1 610-669-1102",
        jobTitle: "CTO",
        companyId: companies[1].id,
        city: "Malvern",
        state: "PA",
        country: "United States",
        notes: "Overseeing digital transformation initiative. Budget authority for technology vendors.",
      },
      {
        firstName: "Ralph",
        lastName: "Hamers",
        email: "r.hamers@ubs.com",
        phone: "+41 44 234 1112",
        jobTitle: "Group CEO",
        companyId: companies[2].id,
        city: "Zurich",
        state: "ZH",
        country: "Switzerland",
        notes: "Former ING CEO. Driving digital-first strategy across UBS.",
      },
      {
        firstName: "Anna",
        lastName: "Weber",
        email: "a.weber@ubs.com",
        phone: "+41 44 234 1215",
        jobTitle: "Head of Wealth Management Technology",
        companyId: companies[2].id,
        city: "Zurich",
        state: "ZH",
        country: "Switzerland",
        notes: "Key contact for wealth management platform decisions. Reports directly to Wealth Management CEO.",
      },
      {
        firstName: "Cyrus",
        lastName: "Taraporevala",
        email: "c.taraporevala@ssga.com",
        phone: "+1 617-786-3001",
        jobTitle: "President & CEO",
        companyId: companies[3].id,
        city: "Boston",
        state: "MA",
        country: "United States",
        notes: "Leading State Street's asset management business. Focus on ESG and index strategies.",
      },
      {
        firstName: "David",
        lastName: "Perlman",
        email: "d.perlman@ntrs.com",
        phone: "+1 312-630-6001",
        jobTitle: "President, Asset Management",
        companyId: companies[4].id,
        city: "Chicago",
        state: "IL",
        country: "United States",
        notes: "Oversees $1.2T in AUM. Interested in operational efficiency solutions.",
      },
      {
        firstName: "Michael",
        lastName: "Greenwald",
        email: "m.greenwald@crd.com",
        phone: "+1 781-622-1001",
        jobTitle: "EVP, Sales",
        companyId: companies[5].id,
        city: "Boston",
        state: "MA",
        country: "United States",
        notes: "Partnership contact for Charles River. Strong relationships across buy-side.",
      },
      {
        firstName: "Christian",
        lastName: "Kromann",
        email: "c.kromann@simcorp.com",
        phone: "+45 35 44 88 01",
        jobTitle: "CEO",
        companyId: companies[6].id,
        city: "Copenhagen",
        state: "",
        country: "Denmark",
        notes: "Leading SimCorp's cloud transformation. Open to strategic partnerships.",
      },
      {
        firstName: "Andreas",
        lastName: "Mueller",
        email: "a.mueller@temenos.com",
        phone: "+41 22 708 11 51",
        jobTitle: "Managing Director, Wealth",
        companyId: companies[7].id,
        city: "Geneva",
        state: "",
        country: "Switzerland",
        notes: "Leads wealth management solutions. Key contact for Swiss private banks.",
      },
      {
        firstName: "Bill",
        lastName: "Stone",
        email: "b.stone@sscinc.com",
        phone: "+1 860-298-4501",
        jobTitle: "Chairman & CEO",
        companyId: companies[8].id,
        city: "Windsor",
        state: "CT",
        country: "United States",
        notes: "Founder and CEO. Active in M&A - acquired Advent, Eze, and Blue Prism.",
      },
    ])
    .returning()

  console.log(`✅ Inserted ${contacts.length} contacts`)

  // Insert deals
  const now = new Date()
  const deals = await db
    .insert(dealsTable)
    .values([
      {
        title: "BlackRock - Portfolio Analytics Platform",
        value: 2500000,
        stage: "proposal",
        probability: 60,
        expectedCloseDate: new Date(now.getTime() + 60 * 24 * 60 * 60 * 1000),
        companyId: companies[0].id,
        contactId: contacts[1].id,
        description: "Implementation of advanced portfolio analytics and risk management capabilities to complement Aladdin.",
      },
      {
        title: "Vanguard - Operations Transformation",
        value: 4200000,
        stage: "negotiation",
        probability: 75,
        expectedCloseDate: new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000),
        companyId: companies[1].id,
        contactId: contacts[3].id,
        description: "Multi-year engagement to modernize back-office operations and implement straight-through processing.",
      },
      {
        title: "UBS - Wealth Platform Integration",
        value: 3800000,
        stage: "qualification",
        probability: 40,
        expectedCloseDate: new Date(now.getTime() + 90 * 24 * 60 * 60 * 1000),
        companyId: companies[2].id,
        contactId: contacts[5].id,
        description: "Integration services for new wealth management platform across European operations.",
      },
      {
        title: "State Street - Data Management Solution",
        value: 1800000,
        stage: "proposal",
        probability: 55,
        expectedCloseDate: new Date(now.getTime() + 45 * 24 * 60 * 60 * 1000),
        companyId: companies[3].id,
        contactId: contacts[6].id,
        description: "Enterprise data management and analytics solution for investment operations.",
      },
      {
        title: "Northern Trust - Cloud Migration",
        value: 2200000,
        stage: "prospecting",
        probability: 25,
        expectedCloseDate: new Date(now.getTime() + 120 * 24 * 60 * 60 * 1000),
        companyId: companies[4].id,
        contactId: contacts[7].id,
        description: "Cloud infrastructure assessment and migration strategy for asset management systems.",
      },
      {
        title: "Charles River - API Integration Services",
        value: 950000,
        stage: "closed-won",
        probability: 100,
        expectedCloseDate: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000),
        actualCloseDate: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000),
        companyId: companies[5].id,
        contactId: contacts[8].id,
        description: "API development and integration services for Charles River IMS connectivity.",
      },
      {
        title: "SimCorp - Dimension Upgrade Consulting",
        value: 1200000,
        stage: "negotiation",
        probability: 70,
        expectedCloseDate: new Date(now.getTime() + 25 * 24 * 60 * 60 * 1000),
        companyId: companies[6].id,
        contactId: contacts[9].id,
        description: "Consulting engagement for SimCorp Dimension upgrade and cloud migration.",
      },
      {
        title: "Temenos - Private Bank Implementation",
        value: 3200000,
        stage: "qualification",
        probability: 35,
        expectedCloseDate: new Date(now.getTime() + 75 * 24 * 60 * 60 * 1000),
        companyId: companies[7].id,
        contactId: contacts[10].id,
        description: "Temenos Wealth implementation for a consortium of Swiss private banks.",
      },
      {
        title: "SS&C - Advent Geneva Migration",
        value: 1600000,
        stage: "closed-won",
        probability: 100,
        expectedCloseDate: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000),
        actualCloseDate: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000),
        companyId: companies[8].id,
        contactId: contacts[11].id,
        description: "Migration services from legacy systems to Advent Geneva portfolio management.",
      },
      {
        title: "Broadridge - Regulatory Reporting",
        value: 890000,
        stage: "prospecting",
        probability: 20,
        expectedCloseDate: new Date(now.getTime() + 100 * 24 * 60 * 60 * 1000),
        companyId: companies[9].id,
        contactId: null,
        description: "Regulatory reporting automation and compliance solution implementation.",
      },
    ])
    .returning()

  console.log(`✅ Inserted ${deals.length} deals`)

  // Insert activities
  const activities = await db
    .insert(activitiesTable)
    .values([
      {
        type: "meeting",
        subject: "Initial Discovery Meeting - Portfolio Analytics",
        description: "Discussed BlackRock's requirements for enhanced portfolio analytics. Sarah expressed interest in real-time risk monitoring capabilities.",
        contactId: contacts[1].id,
        companyId: companies[0].id,
        dealId: deals[0].id,
        completedAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
      },
      {
        type: "call",
        subject: "Follow-up Call - Proposal Review",
        description: "Reviewed initial proposal with Sarah. Requested additional pricing options and timeline scenarios.",
        contactId: contacts[1].id,
        companyId: companies[0].id,
        dealId: deals[0].id,
        completedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
      },
      {
        type: "email",
        subject: "Vanguard - Contract Negotiation Update",
        description: "Sent revised contract terms addressing Michelle's feedback on SLA requirements and implementation timeline.",
        contactId: contacts[3].id,
        companyId: companies[1].id,
        dealId: deals[1].id,
        completedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
      },
      {
        type: "meeting",
        subject: "UBS Executive Presentation",
        description: "Presented solution overview to UBS wealth management technology leadership. Positive reception, follow-up meeting scheduled.",
        contactId: contacts[5].id,
        companyId: companies[2].id,
        dealId: deals[2].id,
        completedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
      },
      {
        type: "task",
        subject: "Prepare State Street Proposal",
        description: "Create detailed proposal for data management solution including technical architecture and pricing.",
        contactId: contacts[6].id,
        companyId: companies[3].id,
        dealId: deals[3].id,
        dueDate: new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000),
      },
      {
        type: "call",
        subject: "Northern Trust Introduction Call",
        description: "Initial call with David to discuss cloud migration needs and current infrastructure challenges.",
        contactId: contacts[7].id,
        companyId: companies[4].id,
        dealId: deals[4].id,
        completedAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000),
      },
      {
        type: "note",
        subject: "Charles River Deal Closed",
        description: "Successfully closed API integration deal. Implementation to begin next month. Michael expressed interest in Phase 2 expansion.",
        contactId: contacts[8].id,
        companyId: companies[5].id,
        dealId: deals[5].id,
        completedAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000),
      },
      {
        type: "meeting",
        subject: "SimCorp Technical Workshop",
        description: "Two-day technical workshop with SimCorp team to finalize Dimension upgrade approach and cloud architecture.",
        contactId: contacts[9].id,
        companyId: companies[6].id,
        dealId: deals[6].id,
        completedAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000),
      },
      {
        type: "task",
        subject: "Schedule Temenos Demo",
        description: "Coordinate with Temenos team to schedule Wealth platform demo for private bank consortium.",
        contactId: contacts[10].id,
        companyId: companies[7].id,
        dealId: deals[7].id,
        dueDate: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000),
      },
      {
        type: "email",
        subject: "SS&C Project Completion",
        description: "Sent project completion report and case study draft for approval. Bill interested in future collaboration.",
        contactId: contacts[11].id,
        companyId: companies[8].id,
        dealId: deals[8].id,
        completedAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000),
      },
      {
        type: "task",
        subject: "Research Broadridge Stakeholders",
        description: "Identify key decision makers at Broadridge for regulatory reporting initiative.",
        companyId: companies[9].id,
        dealId: deals[9].id,
        dueDate: new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000),
      },
      {
        type: "call",
        subject: "Weekly Pipeline Review",
        description: "Internal call to review active deals and prioritize next week's activities.",
        completedAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000),
      },
    ])
    .returning()

  console.log(`✅ Inserted ${activities.length} activities`)

  console.log("\n✨ Database seeded successfully!")
}

seed().catch(console.error)
